version: '3.8'
services:
  gateway:
    build:
      context: .
      target: gateway
    image: ${REGISTRY}/dropbox-gateway:${PRODUCT_VERSION}

  auth:
    build:
      context: .
      target: auth
    image: ${REGISTRY}/dropbox-auth:${PRODUCT_VERSION}

  callback:
    build:
      context: .
      target: callback
    image: ${REGISTRY}/dropbox-callback:${PRODUCT_VERSION}
