namespace: "dropbox"
name: "callback"
version: "1.1.1"
address: ":5044"
repl_address: ":3132"
debug: false
registry:
  addresses: [""]
cache:
  type: 2
  address: 127.0.0.1:6379
  username: ""
  password: ""
  database: 5
tracer:
  enable: false
  address: ""
  type: 1
resilience:
  rate_limiter:
    limit: 1000
    iplimit: 100
  circuit_breaker:
    timeout: 2500
cors:
  origins: [""]
logger:
  name: "callback-logger"
  level: 1
  color: true
credentials:
  client_id: ""
  client_secret: ""
  redirect_url: ""
  token_url: "https://api.dropboxapi.com/oauth2/token"
  scopes: [""]
onlyoffice:
  builder:
    document_server_url: ""
    document_server_secret: ""
    document_server_header: ""
    gateway_url: ""
    callback_url: ""
  callback:
    max_size: 210000000000
    upload_timeout: 120
