namespace: "dropbox"
name: "auth"
version: "1.0.0"
address: ":5052"
repl_address: ":5053"
debug: false
persistence:
  url: ""
  type: 1
registry:
  addresses: [""]
tracer:
  enable: false
  address: ""
  type: 1
resilience:
  rate_limiter:
    limit: 500
  circuit_breaker:
    timeout: 2500
logger:
  name: "auth-logger"
  level: 1
  color: true
credentials:
  client_id: ""
  client_secret: ""
  redirect_url: ""
  auth_url: ""
  token_url: ""
  scopes: [""]