namespace: "dropbox"
name: "gateway"
version: "1.0.0"
address: ":6044"
repl_address: ":9999"
debug: false
registry:
  addresses: [""]
  type: 2
cache:
  type: 2
  address: 127.0.0.1:6379
  username: ""
  password: ""
  database: 5
tracer:
  enable: false
  address: "http://127.0.0.1:9411/api/v2/spans"
  type: 1
resilience:
  rate_limiter:
    limit: 1000
    iplimit: 100
  circuit_breaker:
    timeout: 15000
cors:
  origins: [""]
  methods: ["GET", "POST", "DELETE", "OPTIONS", "PUT"]
  headers: ["*"]
  credentials: true
logger:
  name: "gateway-logger"
  level: 1
  color: true
worker:
  addresses: ["0.0.0.0:6379"]
credentials:
  client_id: ""
  client_secret: ""
  redirect_url: ""
  auth_url: "https://www.dropbox.com/oauth2/authorize"
  token_url: "https://api.dropboxapi.com/oauth2/token"
  scopes: [""]
onlyoffice:
  builder:
    document_server_url: ""
    document_server_secret: ""
    document_server_header: ""
    gateway_url: ""
    callback_url: ""
    allowed_downloads: 10
  callback:
    upload_timeout: 120