name: Build dropbox app

run-name: >
     Build dropbox version: ${{ github.event.inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Set version that will be used for images tag'
        type: string
        required: true

env: 
  PRODUCT_VERSION: ${{ github.event.inputs.version }}
          
jobs:
  build:
    name: "Build dropbox: ${{ github.event.inputs.version }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_TEST_REGISTRY }}
          username: ${{ secrets.DOCKER_TEST_USERNAME }}
          password: ${{ secrets.DOCKER_TEST_ACCESS_TOKEN }}
      
      - name: build and push
        env:
          REGISTRY: ${{ secrets.DOCKER_TEST_REGISTRY }}
        run: |
           docker compose build
           docker compose push
